# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 13:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('lalala', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('Users_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
