# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='head',
            field=models.ImageField(default='/static/blog/userimg/default.jpg', upload_to='static/blog/userimg/'),
        ),
    ]
